#!/usr/bin/env bash

set -euvo pipefail

# Optional - only used for print_colorized
source nextlinux-ci/utils

hash pylint || python -m pip install -q pylint

print_colorized INFO "Linting Nextlinux Engine code."; echo

# This is specifically enabling checks because the output is too large to
# fix in one go. As cleanups are done, more checks can be enabled
pylint -s n --disable=all --enable=C0325 nextlinux_engine

print_colorized INFO "Finished linting Nextlinux Engine code."; echo
